title: Shuangjie Zhang
position: Postdoctoral Researcher Associate
affiliation: Texas A&M University
email: szhan209 (at) ucsc.edu
keywords: minimal academic
avatar: ./assets/img/Shuangjie-Zhang.jpg
google_analytics: G-BFJ64HGEP2
favicon: ./assets/img/1.jpeg
favicon_dark: ./assets/img/1.jpeg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
