title: Shuangjie Zhang
position: Ph.D candidate in Statistics
affiliation: UC Santa Cruz
email: szhan209 (at) ucsc.edu
keywords: minimal academic
avatar: ./assets/img/Shuangjie Zhang.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
